
resilience4j:
  circuitbreaker:
    instances:
      authServiceCircuitBreaker:
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 3
        minimumNumberOfCalls: 3
        failureRateThreshold: 100
        waitDurationInOpenState: 30s
        permittedNumberOfCallsInHalfOpenState: 1
        registerHealthIndicator: true

      authServiceTimeLimiter:
        timeoutDuration: 3s
