resilience4j:
  circuitbreaker:
    instances:
      authServiceCircuitBreaker:
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 3
        minimumNumberOfCalls: 3
        failureRateThreshold: 100
        waitDurationInOpenState: 30s
        permittedNumberOfCallsInHalfOpenState: 1
        registerHealthIndicator: true

  timelimiter:
    instances:
      authServiceTimeLimiter:
        timeoutDuration: 3s

  ratelimiter:
    instances:
      authServiceRateLimiter:
        limitForPeriod: 5        # maximum 5 login attempts
        limitRefreshPeriod: 1m   # per 1 minute
        timeoutDuration: 500ms   # wait time for a permit
